name: axial-modeling
channels:
  - conda-forge
dependencies:
  - python=3.12
  - tmux=3.8
  - gmsh=4.15
  - libglu
  - h5py
  - numpy
  - matplotlib
  - scipy
  - pymupdf
  - pyyaml
  - pytest
  - ruff
  - pre-commit
  - pip
  - pip:
      - -e ".[dev]"
      - gmsh==4.15.2
